# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Helpful symbols
# î‚¶î‚´î®´ğŸ”´ğŸŸ¢
# î«¼îœ¥îœ‚ï˜

add_newline = false

# format = """$all"""
format = """
$status\
$os\
$directory\
$git_branch\
$container\
$hostname\
$username\
$sudo\
$localip\
$docker_context\
$nodejs\
$package\
$python\
$rust\
$shlvl\
$fill\
$cmd_duration\
$time\
$character\
"""

[line_break]
disabled = false

[status]
disabled = false
# symbol = '[î®´](fg:'
# success_symbol = 'î®´'
# symbol = 'ğŸ”´'
# symbol = '[ğŸ”´](bg:#ffffff)'
# symbol = '[î‚¶](bg:none fg:#fc5d7c)[$status](bold fg:#000000 bg:#fc5d7c)'
# symbol = '[$status](bold fg:#fc5d7c)'
# symbol = '[$status](bold fg:#fc5d7c) '
symbol = '[$status $common_meaning](bold fg:red) '
# success_symbol = 'ğŸŸ¢'
# success_symbol = '[î‚¶](bg:none fg:#9ed072)[$status ](fg:#000000 bg:#9ed072)'
# success_symbol = '[$status](fg:#9ed072)'
# map_symbol = true
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[î‚´](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
format = '$symbol'
# style = 'fg: #000000 '
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[î‚´](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
# format = '[î‚¶](bg:none fg:#bbbbbb)[ $symbol $status ]($style)'
# map_symbol = true
# style = 'fg: #000000 bg:#444444'
# style = 'bg:#bbbbbb'

[time]
disabled = false
# format="[ğŸ•’ $time]($style)"
format="[$time]($style)"
time_format = "%a %Y-%m-%d %T%z" #change to %R to only have HH:MM
style = "italic #808080"

[username]
style_user = "fg:blue"
style_root = "bold fg:red"
# format = "[ğŸ§‘ $user]($style)"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname ]($style)"
disabled = false
style = "fg:cyan"

[os]
# format = "[ ğŸ’» $name]($style)"
# format = "[$symbol $name ]($style)"
format = "[$symbol]($style) "
style = "fg:#ff7400"
disabled = false

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[docker_context]
only_with_files = false
# format = '[ğŸ‹ $context ]($style)'
format = '[ğŸ‹ $context ]($style)'
disabled = false
style = "fg:blue"

[localip]
disabled = false
ssh_only = false
# format = "[ ğŸŒ ($localipv4) ]($style)"
format = " [($localipv4) ]($style)"
style = "fg:purple"

[character]
success_symbol = "\n[â–¶](white)"
error_symbol = "\n[â–¶](red)"
# success_symbol = "\n[â¤](white)"
# error_symbol = "\n[â¤](red)"
# success_symbol = "\n[â±](white)"
# error_symbol = "\n[â±](red)"
# success_symbol = "[->](white)"
# error_symbol = "[->](red)"
# success_symbol = "\n[âœ](white)"
# error_symbol = "\n[âœ](red)"
# success_symbol = "\n[ïƒš](white)"
# error_symbol = "\n[ïƒš](red)"
# success_symbol = "\n[î‚°](white)"
# error_symbol = "\n[î‚°](red)"
# success_symbol = ""
# error_symbol = ""

[git_branch]
# symbol = "ğŸŒ± "
truncation_length = 8
truncation_symbol = "â€¦"
# ignore_branches = ["master", "main"]
# Icons: î«¼îœ¥îœ‚ï˜
format = "[ï˜ $branch ]($style)"
style = "fg:green"

# [git_commit]
# disabled = false
# # commit_hash_length = 4
# # tag_symbol = "ğŸ”– "
# # format = "[\\($hash\\) \\($tag\\)]($style)"
# format = "[\\($tag\\)]($style)"
# style = "fg:#9ed072"

# [git_status]
# # format="[î‚¶](fg:#ffffff bg:none)[ğŸ¥¶](fg:#282c34 )[î‚´ ](fg:#ffffff )[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )[î‚´](fg:#4da0ff bg:none)"
# # format="(fg:#ffffff )[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )[î‚´](fg:#9ed072 bg:none)"
# format="[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )"
# conflicted = "âš "
# ahead = "->"
# behind = "<-"
# diverged = "ğŸ˜µ"
# up_to_date = "âœ”"
# untracked = "+"
# stashed = "ğŸ“¦"
# modified = "*"
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘ï¸"
# style = "fg:#9ed072"
# disabled = false

# [git_state]
# rebase = "REBASING"
# merge =	"MERGING"
# revert = "REVERTING"
# cherry_pick = "CHERRY-PICKING"
# bisect = "BISECTING"
# am = "AM"
# am_or_rebase = "AM/REBASE"
# style =	"yellow"
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# disabled = false

[directory]
# format = "[ğŸ“‚ $path ]($style)"
fish_style_pwd_dir_length = 2
format = "[$path ]($style)"
style = "fg:yellow"
truncation_length = 1
# truncation_symbol = "â€¦"

[package] 
symbol = "ğŸ“¦"
disabled = true
style = "fg:#000000 "

[python]
# symbol = "ğŸ"
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style) '
style = "fg:green"

[rust]
symbol = "ğŸ¦€"
format = '[$symbol $version]($style)'
style = "fg:#f39660"

[fill]
symbol = ' '

# [custom.emoji]
# description = "Displays a (pseudo) random emoji for each prompt"
# command = "EMOJIS=(â›µï¸ ğŸ›° ğŸª ğŸš€ ğŸ§¡ ğŸ”­ ğŸŒ ğŸ’« â˜„ï¸ âœ¨ ğŸŒ  ğŸŒŒ â­ï¸); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# when = "1"
# shell = ["cmd /C"]
# format = "$output"

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = '[$duration ](bold #808080)'

[shlvl]
disabled = false
format = '[nested: $shlvl](italic)'
threshold = 2

[sudo]
disabled = false
format = '[*](bold blue)'

[container]
format = '[â¬¢](cyan)'
