# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Helpful symbols
# î‚¶î‚´î®´ğŸ”´ğŸŸ¢
# î«¼îœ¥îœ‚ï˜

add_newline = false

# format = """$all"""
format = """
$status\
$directory\
$git_branch\
$username\
$hostname\
$os\
$localip\
$docker_context\
$nodejs\
$package\
$python\
$rust\
$fill\
$time\
$character\
"""

[line_break]
disabled = false

[status]
disabled = false
# symbol = '[î®´](fg:'
# success_symbol = 'î®´'
# symbol = 'ğŸ”´'
# symbol = '[ğŸ”´](bg:#ffffff)'
# symbol = '[î‚¶](bg:none fg:#fc5d7c)[$status](bold fg:#000000 bg:#fc5d7c)'
# symbol = '[$status](bold fg:#fc5d7c)'
symbol = '[$status](bold fg:#fc5d7c) '
# success_symbol = 'ğŸŸ¢'
# success_symbol = '[î‚¶](bg:none fg:#9ed072)[$status ](fg:#000000 bg:#9ed072)'
# success_symbol = '[$status](fg:#9ed072)'
# map_symbol = true
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[î‚´](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
format = '$symbol'
# style = 'fg: #000000 '
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[î‚´](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
# format = '[î‚¶](bg:none fg:#bbbbbb)[ $symbol $status ]($style)'
# map_symbol = true
# style = 'fg: #000000 bg:#444444'
# style = 'bg:#bbbbbb'

[time]
disabled = false
# format="[ğŸ•’ $time]($style)"
format="[$time]($style)"
time_format = "%a %Y-%m-%d %T%z" #change to %R to only have HH:MM
style="fg:black"

[username]
style_user = "fg:purple"
style_root = "bold fg:red"
# format = "[ğŸ§‘ $user]($style)"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname ]($style)"
disabled = false
style = "fg:purple"

[os]
# format = "[ ğŸ’» $name]($style)"
format = "[$name ]($style)"
style = "fg:#f39660"
disabled = false

[docker_context]
only_with_files = false
# format = '[ğŸ‹ $context ]($style)'
format = '[ğŸ‹ $context ]($style)'
disabled = false
style = "fg:blue"

[localip]
disabled = false
ssh_only = false
# format = "[ ğŸŒ ($localipv4) ]($style)"
format = "[($localipv4) ]($style)"
style = "fg:cyan"

[character]
# success_symbol = "[->](white)"
# error_symbol = "[->](red)"
# success_symbol = "[âœ](white)"
# error_symbol = "[âœ](red)"
success_symbol = "\n[ïƒš](white)"
error_symbol = "\n[ïƒš](red)"

[git_branch]
# symbol = "ğŸŒ± "
truncation_length = 8
truncation_symbol = "â€¦"
# ignore_branches = ["master", "main"]
# Icons: î«¼îœ¥îœ‚ï˜
format = "[ï˜ $branch ]($style)"
style = "fg:green"

# [git_commit]
# disabled = false
# # commit_hash_length = 4
# # tag_symbol = "ğŸ”– "
# # format = "[\\($hash\\) \\($tag\\)]($style)"
# format = "[\\($tag\\)]($style)"
# style = "fg:#9ed072"

# [git_status]
# # format="[î‚¶](fg:#ffffff bg:none)[ğŸ¥¶](fg:#282c34 )[î‚´ ](fg:#ffffff )[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )[î‚´](fg:#4da0ff bg:none)"
# # format="(fg:#ffffff )[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )[î‚´](fg:#9ed072 bg:none)"
# format="[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )"
# conflicted = "âš "
# ahead = "->"
# behind = "<-"
# diverged = "ğŸ˜µ"
# up_to_date = "âœ”"
# untracked = "+"
# stashed = "ğŸ“¦"
# modified = "*"
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘ï¸"
# style = "fg:#9ed072"
# disabled = false

# [git_state]
# rebase = "REBASING"
# merge =	"MERGING"
# revert = "REVERTING"
# cherry_pick = "CHERRY-PICKING"
# bisect = "BISECTING"
# am = "AM"
# am_or_rebase = "AM/REBASE"
# style =	"yellow"
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# disabled = false

[directory]
# format = "[ğŸ“‚ $path ]($style)"
fish_style_pwd_dir_length = 1
format = "[$path ]($style)"
style = "fg:yellow"
truncation_length = 2
# truncation_symbol = "â€¦"

[package] 
symbol = "ğŸ“¦"
disabled = true
style = "fg:#000000 "

[python]
# symbol = "ğŸ"
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style) '
style = "fg:green"

[rust]
symbol = "ğŸ¦€"
format = '[ via $symbol($version )]($style)'
style = "fg:#000000 "

[fill]
symbol = ' '

# [custom.emoji]
# description = "Displays a (pseudo) random emoji for each prompt"
# command = "EMOJIS=(â›µï¸ ğŸ›° ğŸª ğŸš€ ğŸ§¡ ğŸ”­ ğŸŒ ğŸ’« â˜„ï¸ âœ¨ ğŸŒ  ğŸŒŒ â­ï¸); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# when = "1"
# shell = ["cmd /C"]
# format = "$output"
