# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Helpful symbols
# î‚¶î‚´î®´ğŸ”´ğŸŸ¢
# î«¼îœ¥îœ‚ï˜

add_newline = false

# format = """$all"""
format = """
$status\
$time\
$directory\
[ ](fg:#000000 bg:#9ed072)\
$git_branch\
$git_commit\
$git_status\
$nodejs\
$package\
$python\
$rust\
[ ](fg:#000000 bg:#9ed072)\
$username\
$hostname\
$os\
$docker_context\
$localip\
[î‚´](fg:#f39660 bg:none)
$character\
"""

[line_break]
disabled = false

[time]
disabled = false
format="[ ğŸ•’](fg:#fc5d7c bg:#fc5d7c)[ $time ]($style)"
# time_format = "%T" #change to %R to only have HH:MM
time_format = "%a %Y-%m-%d %T%z" #change to %R to only have HH:MM
style="fg:#000000 bg:#fc5d7c"

[username]
style_user = "fg:#000000 bg:#f39660"
style_root = "bold fg:#000000 bg:#f39660"
format = "[ ğŸ§‘ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname]($style)"
disabled = false
style = "fg:#000000 bg:#f39660"

[os]
format = "[ ğŸ’» $name]($style)"
style = "fg:#000000 bg:#f39660"
disabled = false

[docker_context]
format = '[ ğŸ‹ $context](blue bold)'
disabled = false
style = "fg:#000000 bg:#f39660"

[localip]
disabled = false
ssh_only = false
format = "[ ğŸŒ ($localipv4) ]($style)"
style = "fg:#000000 bg:#f39660"

[character]
# success_symbol = "[->](white)"
# error_symbol = "[->](red)"
# success_symbol = "[âœ](white)"
# error_symbol = "[âœ](red)"
success_symbol = "[ïƒš](white)"
error_symbol = "[ïƒš](red)"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 32
truncation_symbol = "â€¦"
# ignore_branches = ["master", "main"]
# Icons: î«¼îœ¥îœ‚ï˜
format = "[ï˜ $branch]($style)"
style = "fg:#000000 bg:#9ed072"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "
format = "[\\($hash\\) \\($tag\\)]($style)"
style = "fg:#000000 bg:#9ed072"

[git_status]
# format="[î‚¶](fg:#ffffff bg:none)[ğŸ¥¶](fg:#282c34 bg:#ffffff)[î‚´ ](fg:#ffffff bg:#4da0ff)[$modified](fg:#282c34 bg:#4da0ff)[$untracked](fg:#282c34 bg:#4da0ff)[$staged](fg:#282c34 bg:#4da0ff)[$renamed](fg:#282c34 bg:#4da0ff)[î‚´](fg:#4da0ff bg:none)"
# format="(fg:#ffffff bg:#9ed072)[$modified](fg:#282c34 bg:#9ed072)[$untracked](fg:#282c34 bg:#9ed072)[$staged](fg:#282c34 bg:#9ed072)[$renamed](fg:#282c34 bg:#9ed072)[î‚´](fg:#9ed072 bg:none)"
format="[$modified](fg:#282c34 bg:#9ed072)[$untracked](fg:#282c34 bg:#9ed072)[$staged](fg:#282c34 bg:#9ed072)[$renamed](fg:#282c34 bg:#9ed072)"
conflicted = "âš "
ahead = "->"
behind = "<-"
diverged = "ğŸ˜µ"
up_to_date = "âœ”"
untracked = "+"
stashed = "ğŸ“¦"
modified = "*"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ï¸"
style = "fg:#000000 bg:#9ed072"
disabled = false

# [git_state]
# rebase = "REBASING"
# merge =	"MERGING"
# revert = "REVERTING"
# cherry_pick = "CHERRY-PICKING"
# bisect = "BISECTING"
# am = "AM"
# am_or_rebase = "AM/REBASE"
# style =	"yellow"
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# disabled = false


[directory]
format = "[ ğŸ“‚ $path ]($style)"
style = "fg:#000000 bg:#e7c664"
truncation_length = 3
truncate_to_repo=false
home_symbol = "~"

[package] 
symbol = "ğŸ“¦"
disabled = true
style = "fg:#000000 bg:#9ed072"

[python]
# symbol = "ğŸ"
format = '[ via ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "fg:#000000 bg:#9ed072"

[rust]
symbol = "ğŸ¦€"
format = '[ via $symbol($version )]($style)'
style = "fg:#000000 bg:#9ed072"

[status]
disabled = false
# symbol = '[î®´](fg:'
# success_symbol = 'î®´'
symbol = 'ğŸ”´'
success_symbol = 'ğŸŸ¢'
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[î‚´](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
format = '[î‚¶](bg:none fg:#76cce0)[ $symbol $status ]($style)'
# map_symbol = true
# style = 'fg: #000000 bg:#444444'
style = 'bg:#76cce0'

# [custom.emoji]
# description = "Displays a (pseudo) random emoji for each prompt"
# command = "EMOJIS=(â›µï¸ ğŸ›° ğŸª ğŸš€ ğŸ§¡ ğŸ”­ ğŸŒ ğŸ’« â˜„ï¸ âœ¨ ğŸŒ  ğŸŒŒ â­ï¸); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# when = "1"
# shell = ["cmd /C"]
# format = "$output"
